controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - arm_joint
        # - garra_joint
