controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_joint_position_controller:
      type: position_controllers/JointPositionController
      joint: 
        - arm_joint
      command_interfaces:
        - position
